import { Zap, Layers, Layers2 } from "lucide-react";

export const plansData = [
  {
    id: "basic",
    name: "Basic plan",
    price: 10,
    description: "Our most popular plan.",
    icon: Zap,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
  },
  {
    id: "business",
    name: "Business plan",
    price: 20,
    description: "Best for growing teams.",
    icon: Layers2,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
  },
  {
    id: "enterprise",
    name: "Enterprise plan",
    price: 40,
    description: "Best for large teams.",
    icon: Layers,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
  },
];

export const featuresData = [
  {
    name: "Landscape, Portrait & Custom screen Support",
    basic: true,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "More than 100 App",
    basic: true,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Full player offline operation",
    basic: false,
    business: false,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Extensive and advanced content scheduling",
    basic: true,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Published your content to all supported platform",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Create multi region layout",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Animated Content transition",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Animated Content transition",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: true,
  },
  {
    name: "Animated Content transition",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: false,
  },
  {
    name: "Animated Content transition",
    basic: false,
    business: true,
    enterprise: true,
    hasInfo: false,
  },
];
export const monthlyPlansData = [
  {
    id: "basic",
    name: "Basic plan",
    price: 10,
    description: "Our most popular plan.",
    icon: Zap,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "100 credits / monthly",
  },
  {
    id: "pro",
    name: "Pro plan",
    price: 20,
    description: "Our most popular plan.",
    icon: Layers2,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "2000 credits / monthly",
  },
  {
    id: "bussiness",
    name: "Bussiness plan",
    price: 30,
    description: "Our most popular plan.",
    icon: Layers,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "4000 credits / monthly",
  },
];
export const yearlyPlansData = [
  {
    id: "basic",
    name: "Basic plan",
    price: 100,
    description: "Our most popular plan.",
    icon: Zap,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "1000 credits / yearly",
  },
  {
    id: "pro",
    name: "Pro plan",
    price: 200,
    description: "Our most popular plan.",
    icon: Layers2,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "20000 credits / yearly",
  },
  {
    id: "bussiness",
    name: "Bussiness plan",
    price: 300,
    description: "Our most popular plan.",
    icon: Layers,
    iconColor: "text-purple-300",
    iconBg: "bg-purple-25",
    creditCount: "40000 credits / yearly",
  },
];
